[package]
name = "raid_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12.4"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tokio-postgres = "0.7"
dotenvy = "0.15"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.4"
